DormitoryWebProject/Controllers/CMS/CMSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DormitoryWebProject.Controllers.CMS
{
    public class CMSController : Controller
    {
        // GET: CMS
        public ActionResult Index()
        {
            return View("CMSHome");
        }
    }
}

DormitoryWebProject/Controllers/CMS/ChiTietKTXController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DormitoryWebProject.Models;

namespace DormitoryWebProject.Controllers.CMS
{
    public class ChiTietKTXController : Controller
    {
        private DormitoryDBContext db = new DormitoryDBContext();

        // GET: ChiTietKTX
        public ActionResult Index()
        {
            var chiTietKTX = db.ChiTietKTX.Include(c => c.KTX);
            return View(chiTietKTX.ToList());
        }

        // GET: ChiTietKTX/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietKTX chiTietKTX = db.ChiTietKTX.Find(id);
            if (chiTietKTX == null)
            {
                return HttpNotFound();
            }
            return View(chiTietKTX);
        }

        // GET: ChiTietKTX/Create
        public ActionResult Create()
        {
            ViewBag.MaKTX = new SelectList(db.KTX, "MaKTX", "TenKTX");
            return View();
        }

        // POST: ChiTietKTX/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaChiTietKTX,Rated,GiaThueThapNhat,GiaThueCaoNhat,MoTaKTX,pictureUpload1,pictureUpload2,pictureUpload3,pictureUpload4,pictureUpload5,MaKTX")] ChiTietKTX chiTietKTX)
        {
            if (ModelState.IsValid)
            {
                //Picture Handle
                string filename1 = Path.GetFileName(chiTietKTX.pictureUpload1.FileName);
                string filename2 = Path.GetFileName(chiTietKTX.pictureUpload2.FileName);
                string filename3 = Path.GetFileName(chiTietKTX.pictureUpload3.FileName);
                string filename4 = Path.GetFileName(chiTietKTX.pictureUpload4.FileName);
                string filename5 = Path.GetFileName(chiTietKTX.pictureUpload5.FileName);
                string path1 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename1);
                string path2 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename2);
                string path3 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename3);
                string path4 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename4);
                string path5 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename5);
                chiTietKTX.pictureUpload1.SaveAs(path1);
                chiTietKTX.pictureUpload2.SaveAs(path2);
                chiTietKTX.pictureUpload3.SaveAs(path3);
                chiTietKTX.pictureUpload4.SaveAs(path4);
                chiTietKTX.pictureUpload5.SaveAs(path5);
                string pathInDb1 = "/assets/images/CMS/chiTietKTX/" + filename1;
                string pathInDb2 = "/assets/images/CMS/chiTietKTX/" + filename2;
                string pathInDb3 = "/assets/images/CMS/chiTietKTX/" + filename3;
                string pathInDb4 = "/assets/images/CMS/chiTietKTX/" + filename4;
                string pathInDb5 = "/assets/images/CMS/chiTietKTX/" + filename5;
                chiTietKTX.picturePath1 = pathInDb1;
                chiTietKTX.picturePath2 = pathInDb2;
                chiTietKTX.picturePath3 = pathInDb3;
                chiTietKTX.picturePath4 = pathInDb4;
                chiTietKTX.picturePath5 = pathInDb5;

                db.ChiTietKTX.Add(chiTietKTX);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKTX = new SelectList(db.KTX, "MaKTX", "TenKTX", chiTietKTX.MaKTX);
            return View(chiTietKTX);
        }

        // GET: ChiTietKTX/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietKTX chiTietKTX = db.ChiTietKTX.Find(id);
            if (chiTietKTX == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKTX = new SelectList(db.KTX, "MaKTX", "TenKTX", chiTietKTX.MaKTX);
            return View(chiTietKTX);
        }

        // POST: ChiTietKTX/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaChiTietKTX,Rated,GiaThueThapNhat,GiaThueCaoNhat,MoTaKTX,pictureUpload1,pictureUpload2,pictureUpload3,pictureUpload4,pictureUpload5,MaKTX")] ChiTietKTX chiTietKTX)
        {
            if (ModelState.IsValid)
            {
                //Picture Handle
                string filename1 = Path.GetFileName(chiTietKTX.pictureUpload1.FileName);
                string filename2 = Path.GetFileName(chiTietKTX.pictureUpload2.FileName);
                string filename3 = Path.GetFileName(chiTietKTX.pictureUpload3.FileName);
                string filename4 = Path.GetFileName(chiTietKTX.pictureUpload4.FileName);
                string filename5 = Path.GetFileName(chiTietKTX.pictureUpload5.FileName);
                string path1 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename1);
                string path2 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename2);
                string path3 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename3);
                string path4 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename4);
                string path5 = Path.Combine(Server.MapPath("~/assets/images/CMS/chiTietKTX"), filename5);
                chiTietKTX.pictureUpload1.SaveAs(path1);
                chiTietKTX.pictureUpload2.SaveAs(path2);
                chiTietKTX.pictureUpload3.SaveAs(path3);
                chiTietKTX.pictureUpload4.SaveAs(path4);
                chiTietKTX.pictureUpload5.SaveAs(path5);
                string pathInDb1 = "/assets/images/CMS/chiTietKTX/" + filename1;
                string pathInDb2 = "/assets/images/CMS/chiTietKTX/" + filename2;
                string pathInDb3 = "/assets/images/CMS/chiTietKTX/" + filename3;
                string pathInDb4 = "/assets/images/CMS/chiTietKTX/" + filename4;
                string pathInDb5 = "/assets/images/CMS/chiTietKTX/" + filename5;
                chiTietKTX.picturePath1 = pathInDb1;
                chiTietKTX.picturePath2 = pathInDb2;
                chiTietKTX.picturePath3 = pathInDb3;
                chiTietKTX.picturePath4 = pathInDb4;
                chiTietKTX.picturePath5 = pathInDb5;

                db.Entry(chiTietKTX).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKTX = new SelectList(db.KTX, "MaKTX", "TenKTX", chiTietKTX.MaKTX);
            return View(chiTietKTX);
        }

        // GET: ChiTietKTX/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChiTietKTX chiTietKTX = db.ChiTietKTX.Find(id);
        //    if (chiTietKTX == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(chiTietKTX);
        //}

        // POST: ChiTietKTX/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChiTietKTX chiTietKTX = db.ChiTietKTX.Find(id);
            if (chiTietKTX == null)
            {
                return HttpNotFound();
            }
            db.ChiTietKTX.Remove(chiTietKTX);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DormitoryWebProject/Controllers/CMS/ChucVuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DormitoryWebProject.Models;

namespace DormitoryWebProject.Controllers.CMS
{
    public class ChucVuController : Controller
    {
        private DormitoryDBContext db = new DormitoryDBContext();

        // GET: ChucVu
        public ActionResult Index()
        {
            return View(db.ChucVu.ToList());
        }

        // GET: ChucVu/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(id);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // GET: ChucVu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChucVu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaChucVu,TenChucVu")] ChucVu chucVu)
        {
            if (ModelState.IsValid)
            {
                db.ChucVu.Add(chucVu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chucVu);
        }

        // GET: ChucVu/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVu.Find(id);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // POST: ChucVu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaChucVu,TenChucVu")] ChucVu chucVu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chucVu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chucVu);
        }

        // GET: ChucVu/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChucVu chucVu = db.ChucVu.Find(id);
        //    if (chucVu == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(chucVu);
        //}

        // POST: ChucVu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChucVu chucVu = db.ChucVu.Find(id);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            db.ChucVu.Remove(chucVu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DormitoryWebProject/Controllers/CMS/KTXController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DormitoryWebProject.Models;

namespace DormitoryWebProject.Controllers.CMS
{
    public class KTXController : Controller
    {
        private DormitoryDBContext db = new DormitoryDBContext();

        // GET: KTX
        public ActionResult Index()
        {
            return View(db.KTX.ToList());
        }

        // GET: KTX/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KTX kTX = db.KTX.Find(id);
            if (kTX == null)
            {
                return HttpNotFound();
            }
            return View(kTX);
        }

        // GET: KTX/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KTX/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKTX,TenKTX,DiaChi,SDTLienHe,Email")] KTX kTX)
        {
            if (ModelState.IsValid)
            {
                db.KTX.Add(kTX);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kTX);
        }

        // GET: KTX/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KTX kTX = db.KTX.Find(id);
            if (kTX == null)
            {
                return HttpNotFound();
            }
            return View(kTX);
        }

        // POST: KTX/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKTX,TenKTX,DiaChi,SDTLienHe,Email")] KTX kTX)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kTX).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kTX);
        }

        // GET: KTX/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    KTX kTX = db.KTX.Find(id);
        //    if (kTX == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(kTX);
        //}

        // POST: KTX/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KTX kTX = db.KTX.Find(id);
            if (kTX == null)
            {
                return HttpNotFound();
            }
            db.KTX.Remove(kTX);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DormitoryWebProject/Views/CMS/KTX/Create.cshtml
@model DormitoryWebProject.Models.KTX

@{
    ViewBag.Title = "Create";
    ViewBag.formheader = "";
    Layout = "~/Views/Shared/Main/_LayoutFormCMS.cshtml";
}
@using (Html.BeginForm("Create", "KTX", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="card card-dark">
            <div class="card-header">
                <h3 class="card-title">Thêm ký túc xá</h3>
            </div>
            <div class="card-body container">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group row">
                    @Html.LabelFor(model => model.TenKTX, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.TenKTX, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenKTX, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.SDTLienHe, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.SDTLienHe, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SDTLienHe, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="/KTX" class="btn btn-default bg-navy"><i class="ionicons ion-ios-undo-outline"></i> Trở về</a>
                <button class="btn btn-default bg-warning float-right" name="Create" value="Create" type="submit"><i class="fa fa-check"></i> <span>Lưu</span></button>
            </div>
        </div>
    </div>
}

DormitoryWebProject/Views/CMS/KTX/Details.cshtml
@model DormitoryWebProject.Models.KTX

@{
    ViewBag.Title = "Details";
    ViewBag.formheader = "";
    ViewData["aCMS"] = "active";
    Layout = "~/Views/Shared/Main/_LayoutFormCMS.cshtml";

}
<div class="card card-dark">
    <div class="card-header">
        <h3 class="card-title">Chi tiết @Model.TenKTX</h3>
    </div>
    <div class="card-body">
        <div class="row justify-content-end">
            <a href="/KTX/Edit/@Model.MaKTX" class="btn btn-default btn-flat bg-indigo"><i class="ionicons ion-edit"></i> Chỉnh sửa</a>
            <a href="#" class="btn btn-default btn-flat bg-danger ml-1" data-toggle="modal" data-target="#deleteconfirmation"><i class="far fa-trash-alt"></i> Xóa</a>
            <div class="form-horizontal container">
                <div class="form-group row">
                    <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.TenKTX)</label>
                    <div class="col-md-4">
                        @Model.TenKTX
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.DiaChi)</label>
                    <div class="col-md-4">
                        @Model.DiaChi
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.SDTLienHe)</label>
                    <div class="col-md-4">
                        @Model.SDTLienHe
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.Email)</label>
                    <div class="col-md-4">
                        @Model.Email
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="card-footer">
        <a href="/KTX" class="btn btn-default bg-navy"><i class="ionicons ion-ios-undo-outline"></i> Trở về</a>
    </div>
</div>
<div class="modal fade" id="deleteconfirmation">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Xác nhận xóa?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/KTX/Delete/@Model.MaKTX" method="post" style="margin:0;">
                    @Html.AntiForgeryToken()
                    <div>
                        Are you sure you want to delete this item?
                    </div>
                    <div class="mt-3 text-right">
                        <button type="button" class="btn btn-secondary btn-flat" data-dismiss="modal" onclick="closeModalWindow(); return false;">
                            Không, hủy bỏ
                        </button>
                        <button type="submit" class="btn btn-danger" value="Delete" data-commit-action="delete" data-commit-id="@Model.MaKTX">
                            Xóa
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

DormitoryWebProject/Views/CMS/KTX/Edit.cshtml
@model DormitoryWebProject.Models.KTX

@{
    ViewBag.Title = "Edit";
    ViewBag.formheader = "";
    ViewData["aCMS"] = "active";
    Layout = "~/Views/Shared/Main/_LayoutFormCMS.cshtml";
}
@using (Html.BeginForm("Edit", "KTX", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="card card-dark">
        <div class="card-header">
            <h3 class="card-title" style="font-weight:700">Chỉnh sửa Poster</h3>
        </div>
        <div class="card-body">
            <div class="container">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaKTX)
                    <div class="form-group row">
                        @Html.LabelFor(model => model.TenKTX, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenKTX, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenKTX, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.SDTLienHe, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SDTLienHe, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SDTLienHe, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="card-footer">
            <a href="/KTX" class="btn btn-default bg-navy"><i class="ionicons ion-ios-undo-outline"></i> Trở về</a>
            <button type="submit" class="btn btn-default bg-teal float-right" name="Save" value="Save"><i class="fa fa-check"></i> <span>Lưu</span></button>
        </div>
    </div>
}

DormitoryWebProject/Views/CMS/KTX/Index.cshtml
@model IEnumerable<DormitoryWebProject.Models.KTX>

@{
    ViewBag.Title = "Index";
    ViewBag.formheader = "";
    ViewData["aCMS"] = "active";
    Layout = "~/Views/Shared/Main/_LayoutFormCMS.cshtml";
}
@section PageStyle{
    <link href="~/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/assets/css/CMS/KTX/Index.css" rel="stylesheet" />
}
@section PageScript{
    <script src="~/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $(".table").DataTable({
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}
<div class="card card-dark">
    <div class="card-header">
        <h3 class="card-title" style="font-weight:700">Ký túc xá</h3>
        <a href="@Url.Action("Create","KTX")" class="btn btn-primary bg-olive btn-flat btn-xs float-right" style="font-weight:700"><i class="fa fa-plus"></i></a>
    </div>
    <div class="card-body">
        <div class="float-md-right float-sm-none">
            <a href="@Url.Action("Create","KTX")" class="btn btn-primary bg-primary btn-flat btn-sm" style="font-weight:700;border:none"><i class="fa fa-plus"></i> Thêm mới</a>
        </div>
        <table id="KtxDM" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.TenKTX)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DiaChi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SDTLienHe)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.TenKTX, "Details", new { id = item.MaKTX })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DiaChi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SDTLienHe)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>